### ISSUE TITLE
Formatting codes

### ISSUE THREAD

**Issue by WizardCM** [WMCAlliance/BukkitIRCd#1]
Currently, the following colour/formatting codes do not work;

§k Random
§l Bold
§m Strike
§n Underlined
§o Italics
§r Reset

**Comment by WizardCM** [comment]
I have no idea where to add this. Any suggestions would be good.

**Comment by BlaneyXYZ** [comment]
I do not see the use in adding this.

**Comment by WizardCM** [comment]
If someone bolds (etc) something ingame, the plugin should be able to properly filter/format it.
![04-01_22-13-03](https://f.cloud.github.com/assets/941350/42961/e5990f1e-565f-11e2-9fc9-175342ae3535.png)

**Comment by BlaneyXYZ** [comment]
I'm pretty sure this can be achieved in the config.

**Comment by WizardCM** [comment]
This seems like it'll be quite a bit of work.

Currently, the codes are set as a number (possibly a char, though not entirely sure).

Some variables to look into (in IRCd.java)
ircColors
gameColors

**Comment by chyyran** [comment]
The IRC codes are [mIRC Color Codes](http://www.mirc.com/colors.html)

**Comment by Jdbye** [comment]
Those variables are unrelated to other formatting codes than colors, however convertColors handles those as well.
Unless you have changed this, currently convertColors replaces IRC color codes with nothing, it could simply be changed to replace them with the respective Minecraft color codes.
As for ingame messages sent to IRC replacing the codes will have to be added in the same way it's done in the rest of the function.
I haven't looked at the code in a while but if you can't figure it out I'll try to help out.

**Comment by chyyran** [comment]
[A Python gist I made that may help shed some light on this](https://gist.github.com/ron975/5409035/)
Thankfully Python is simple enough to be read by even people who don't know python's syntax :)

I intend to do this in Java for real, I'll be rewriting the method using the logic above

**Comment by chyyran** [comment]
Fixed in pull request #29
