### ISSUE TITLE
if (!message.contains("IRC ")) { // Don't show IRC messages

### ISSUE THREAD

**Issue by WizardCM** [WMCAlliance/BukkitIRCd#10]
Probably the most inefficient method to check for IRC -> ingame messages so they can be cancelled in the staff channel.

This is in the IRCCommandSender.java file.

**Comment by WizardCM** [comment]
Fixed in #31

**Comment by chyyran** [comment]
There is another way to do this, besides regex, that's to use sendMessage() to every online player instea of broadcastMessage() so it doesnt get logged in console.. That, however, requires a heck of a lot more work to do than just using regex to filter out the bad stuff, and sine it has to loop through more objects than just the expressions, might not be as fast (efficient). However, its probably more user friendly. The downside of using sendMessage() is that I have a feeling itll bring a 200 player server to it's knees as it would have to loop through 200 player objects every time someone says something on IRC

**Comment by WizardCM** [comment]
I think the current way is good because it means server owners can filter out things other than the messages.
Out of curiosity, would it also be possible, using a similar regex config option, for items that should be filtered INto the main channel (say, broadcasts & deaths, if you wanted)?

**Comment by chyyran** [comment]
I guess it would be possible, but the best way to do it is probably with a listener.
