### ISSUE TITLE
CRITICAL: Recent commit broke /ircreload or reloading via plugin

### ISSUE THREAD

**Issue by WizardCM** [WMCAlliance/BukkitIRCd#101]
100% caused by  https://github.com/WMCAlliance/BukkitIRCd/commit/a361fb7562a37bd26de9caec66218f5271c017e9 @glguy

Looks like it attempts two connections at the same time or something.

23:58:22 [INFO] [BukkitIRCd] Enabling BukkitIRCd v1.2
23:58:22 [INFO] [BukkitIRCd] Loaded configuration file.
23:58:22 [INFO] [BukkitIRCd] Loaded MOTD file.
23:58:22 [INFO] [BukkitIRCd] Loaded messages file.
23:58:22 [INFO] [BukkitIRCd] Loaded bans file.
23:58:22 [INFO] BukkitIRCd 1.2 by Jdbye is enabled!
23:58:22 [INFO] Successfully enabled BukkitIRCd!
23:58:22 [INFO] [BukkitIRCd] Listening for server connections on port 7099
23:58:23 [INFO] [BukkitIRCd] Attempting connection to bla.bla.net:bla.bla.net
23:58:24 [INFO] [BukkitIRCd] Connected to bla.bla.net:7099
23:58:24 [INFO] IRC Linked to server bla.bla.net.
23:58:25 [WARNING] [BukkitIRCd] Server link failed: java.net.SocketTimeoutException: Read timed out
23:58:25 [INFO] [BukkitIRCd] Lost connection to bla.bla.net:bla.bla.net
23:58:25 [INFO] [BukkitIRCd] Waiting 60 seconds before retrying...
23:58:25 [WARNING] [BukkitIRCd] Server link failed: java.net.SocketException: Socket closed
23:58:25 [INFO] [BukkitIRCd] Waiting 60 seconds before retrying...
23:58:25 [INFO] IRC Split from server bla.bla.net:bla.bla.net.

**Comment by glguy** [comment]
It is almost certainly not that commit because that commit doesn't change the linking socket behavior. I'd like to see the logs from Inspircd when this happened. I'm using the current development branch on three servers linked to two Inspircds all linked together.

Once we have more log output I'd love to help track this down.

**Comment by WizardCM** [comment]
Fixed in https://github.com/WMCAlliance/BukkitIRCd/commit/00c1b474f7069cfd64f7ed3248e65f110fa56315
