### ISSUE TITLE
Kick messages contain newline

### ISSUE THREAD

**Issue by Rikairchy** [WMCAlliance/BukkitIRCd#109]
When kicking a user, either using !kick in the staff channel or in game, it sends a newline in 1.7.4, causing inspIRCd to netsplit. Not Bukkit's default kick command seems to work. A slight .replace should fix it, right?

https://github.com/Bukkit/Bukkit/blob/08c71f24abc214bb6995a7266593dbb2217ddde1/src/main/java/org/bukkit/command/defaults/KickCommand.java

Line 40:
     Command.broadcastCommandMessage(sender, "Kicked player " + player.getName() + ". With reason:\n" + reason);

**Comment by BlaneyXYZ** [comment]
I wasn't able to replicate this, mind trying again for me please.

**Comment by WizardCM** [comment]
Yeah I'm not seeing this on InspIRCd-2.0 either, and didn't have an issue from 1.7.2 to 1.8.3.

**Comment by Rikairchy** [comment]
Bukkit fixed this about a week after I posted an issue in their forums pertaining to this. You guys are slightly late to the party.
