### ISSUE TITLE
/irc command to list all commands

### ISSUE THREAD

**Issue by WizardCM** [WMCAlliance/BukkitIRCd#12]
Put simply

**Comment by Lunaphied** [comment]
Alright, good plan but we need to restrict what commands we let them see by what permissions they have, otherwise they will poke too much.

**Comment by WizardCM** [comment]
I agree, and that wouldn't be too hard to do.

**Comment by BlaneyXYZ** [comment]
Done here https://github.com/WMCAlliance/BukkitIRCd/commit/555f5139cf759f578408501462dc2f254530a4cc
