### ISSUE TITLE
Ident masking

### ISSUE THREAD

**Issue by WizardCM** [WMCAlliance/BukkitIRCd#14]
Ability to hide all but the last two bits of the host with a customizable string.

**Comment by Lunaphied** [comment]
Customizable? How about just randomly generated.

**Comment by WizardCM** [comment]
Whatever we can get working would be great.

**Comment by glguy** [comment]
A version of this is implemented in the dev version using the configuration options: use-host-mask , host-mask-prefix, and if my pull request is accepted host-mask-suffix

**Comment by WizardCM** [comment]
Yep, awesomely done @glguy. Good job! :)
