### ISSUE TITLE
In-game Chat Formatting

### ISSUE THREAD

**Issue by bagheadinc** [WMCAlliance/BukkitIRCd#16]
I'd like to request the ability to change the in-game chat format of text that comes from IRC. Being able to specify the prefix (instead of the default [IRC] one) and being able to set default colors would be very nice.

**Comment by Lunaphied** [comment]
Not very hard at all to implement if another more active team member could
point me to the correct class files where we handle this. That is, not hard
in theroy I seem to remember a bunch of hardcoded stuff before. Another
team member will need to bring me up to date on this.

**Comment by WizardCM** [comment]
This is already possible with the messages.yml in the configuration folder. You can find a version of this on the GitHub (in the res folder https://github.com/WMCAlliance/BukkitIRCd/blob/master/res/messages.yml) as a base. I believe a copy of it is also in the zip on BukkitDev.

**Comment by bagheadinc** [comment]
Ah, I didn't have the messages.yml on my server since I migrated from the original BukkitIRCd. Thanks, exactly what I was looking for! :)

**Comment by WizardCM** [comment]
Not a problem. It was a feature in the original BukkitIRCd, it just wasn't generated with the config so nobody knew about it. I hope on changing that soon. :)

**Comment by Lunaphied** [comment]
OK. I still need someone to get me those resources regardless.
