### ISSUE TITLE
Make IRC nick the Player's displayName

### ISSUE THREAD

**Issue by chyyran** [WMCAlliance/BukkitIRCd#20]
Make the IRC nickname the Player's displayname (`player.getDisplayName()`) instead of (`player.getName()`).

**Comment by WizardCM** [comment]
While this isn't a bad idea, I think providing a configuration option would be better than just changing it for everyone. Not all server owners would want this, but many would.

**Comment by chyyran** [comment]
Of course it should be able to be configured, I'm just putting the idea out there.

**Comment by chyyran** [comment]
See https://github.com/WMCAlliance/BukkitIRCd/issues/25
