### ISSUE TITLE
In latest build (47) where staff channel commands are run as console, the output isn't shown in the channel, but console itself

### ISSUE THREAD

**Issue by WizardCM** [WMCAlliance/BukkitIRCd#28]
http://netbook.home.wizardcm.com:8080/job/BukkitIRCd/47/

 Minecraft (Minecraft@mc.wizardcm.com) has joined #minecraft-staff
<WizardCM> !op
<Minecraft> Command executed.
<WizardCM> !priv
<Minecraft> Command executed.

**Comment by chyyran** [comment]
Fixed in pull request #30
