### ISSUE TITLE
In latest build (56) two connections occur in the link so there is a timeout and disconnect

### ISSUE THREAD

**Issue by WizardCM** [WMCAlliance/BukkitIRCd#34]
http://netbook.home.wizardcm.com:8080/job/BukkitIRCd/56/

Build 50 & earlier
16:45:19 [INFO] BukkitIRCd 1.1 by Jdbye is enabled!
16:45:19 [INFO] Updated BukkitIRCd successfully.
16:45:19 [INFO] [BukkitIRCd] Listening for server connections on port 7099
16:45:20 [INFO] [BukkitIRCd] Attempting connection to sigint.echelon4.net:7099
16:45:20 [INFO] [BukkitIRCd] Connected to sigint.echelon4.net:7099
Everything is fine from here.

Now:

16:33:11 [INFO] [BukkitIRCd] Enabling BukkitIRCd v1.1
16:33:11 [INFO] [BukkitIRCd] Loaded configuration file. Code BukkitIRCdPlugin363.
16:33:11 [INFO] [BukkitIRCd] Saved initial configuration file. Code BukkitIRCdPlugin365.
16:33:11 [INFO] [BukkitIRCd] Loaded MOTD file. Code BukkitIRCdPlugin516.
16:33:11 [INFO] [BukkitIRCd] Loaded messages file. Code BukkitIRCdPlugin464.
16:33:11 [INFO] [BukkitIRCd] Loaded bans file. Code BukkitIRCdPlugin551.
16:33:11 [INFO] BukkitIRCd 1.1 by Jdbye is enabled!
16:33:11 [INFO] Successfully enabled BukkitIRCd!
16:33:11 [INFO] [BukkitIRCd] Listening for server connections on port 7099
16:33:12 [INFO] [BukkitIRCd] Got server connection from THE_OTHER_SERVER_IP
16:33:12 [SEVERE] [BukkitIRCd] Unexpected exception in Thread-BukkitIRCd-InspIRCd: java.lang.NullPointerException
16:33:12 [SEVERE] [BukkitIRCd] Error code IRCd473.
16:33:12 [SEVERE] java.lang.NullPointerException
16:33:12 [SEVERE]       at com.Jdbye.BukkitIRCd.IRCd.run(IRCd.java:392)
16:33:12 [SEVERE]       at java.lang.Thread.run(Thread.java:722)
16:33:12 [SEVERE] Failed to listen on port 7099: java.net.BindException: Address already in use
16:33:13 [INFO] [BukkitIRCd] Got server connection from THE_OTHER_SERVER_IP
16:33:13 [WARNING] [BukkitIRCd] Server link failed: java.io.IOException: Lost connection to server before sending handshake!
16:33:13 [INFO] [BukkitIRCd] Waiting 60 seconds before retrying...

**Comment by WizardCM** [comment]
Here's the result from lsof -i

COMMAND     PID     USER        FD      TYPE    DEVICE      SIZE/OFF    NODE    NAME
java        30641   minecraft   198u    IPv4    2016603730  0t0         TCP     wma.im:47730->THE_OTHER_SERVER_IP:7099 (CLOSE_WAIT)

When it should be

java        30641   minecraft   163u    IPv4    2016984623  0t0         TCP     wma.im:48263->THE_OTHER_SERVER_IP:7099 (ESTABLISHED)

**Comment by chyyran** [comment]
Seems like that NPE at line 392 is causing the connection to drop

**Comment by WizardCM** [comment]
Any idea what change in your recent commits could cause something like this though?

**Comment by chyyran** [comment]
Most likely I left something out when I was adding the prefixes and suffixes. Try a build from before that commit.

I never encountered this error while testing though..

**Comment by chyyran** [comment]
Using the build you posted above in link mode:

![](http://gyazo.com/dee038596975c73116334c6eed261e8a.png)

In standalone:
![](http://gyazo.com/da75a5bba092efbbe459937843efd7bb.png)

[config.yml](https://gist.github.com/ron975/40706667f71f80f4063c)
[messages.yml](https://gist.github.com/ron975/550af7e98b7d1e32fd0f)

I couldn't reproduce the bug, perhaps show me the config with the link passes redacted?

Also, I took a look at [Line 392](https://github.com/WMCAlliance/BukkitIRCd/blob/master/src/com/Jdbye/BukkitIRCd/IRCd.java#L392) and it has something to do with the capabilities, which is extremely odd. Perhaps add some try/catch debug code there to see whats going on.

```
                                    if (line.startsWith("CAPAB START")) {
                                    sendLinkCAPAB();
                                }
```

**Comment by WizardCM** [comment]
So I fixed it locally by running each build from 53 to 56. However, Build 57 (with death messages) errors in the same way as it did before.
I currently have console-filters, group-prefixes and group-suffixes commented out.
Edit: It also happened when I used invalid regex

**Comment by chyyran** [comment]
Does it work with console-filters, group-prefixes and group-suffixes not commented out?

**Comment by WizardCM** [comment]
This works, but if I uncomment group-prefixes, or put "&IRC " in console-filters it breaks.

console-filters: # Filters messages that go into the staff channel. Format is regular expressions.
    - "^IRC.+"
    - "^&3IRC.+"
// group-prefixes: #Prefixes
//  h: "&b"
//  o: "&a"
//  q: "&6"
//  v: "&7"
//  user: "&2"
//group-suffixes: #Suffixes
//  h: ""
//  o: ""
//  q: ""
//  v: ""
(Replace // with a hash, using hash on here makes that text extremely huge)

**Comment by chyyran** [comment]
Try [this build](https://buildhive.cloudbees.com/job/ron975/job/BukkitIRCd/24/). It should at least fix the invalid regex problem.

Also, the regex needs to match the whole string, therefore `.+` at the end.

**Comment by WizardCM** [comment]
In reference to your build;
- say messages come through
- death messages come through
- uncommenting prefixes/suffixes doesn't break anything
- prefixes work perfectly (haven't tested suffixes)

However,
- death messages strip all colours
- say doesn't convert colour codes
- death messages use the name with the irc suffix (ie. WizardCM-mc)

**Comment by WizardCM** [comment]
In short, that build completely gets rid of this issue.

**Comment by chyyran** [comment]
Death and say messages are intended to strip colours, I didn't see any reason to convert those colours, if you want, I'll add a config option to toggle that
