### ISSUE TITLE
"Coloured /say messages" are only coloured pink - they don't convert colour codes (same with colouring turned off)

### ISSUE THREAD

**Issue by WizardCM** [WMCAlliance/BukkitIRCd#42]
color-say-messages: false
![NoColour Example](http://scr.wizrd.tk/scr/22-04_09-13-09.png)

color-say-messages: true
![Coloured Example](http://scr.wizrd.tk/scr/22-04_09-05-47.png)

However, this could be plugin specific: I'm using RoyalCommands and that automatically converts colours in /say

**Comment by chyyran** [comment]
They don't actually convert color codes since I wanted it to match vanilla behavior.

**Comment by WizardCM** [comment]
Then I guess just strip any custom colour codes from it? It'd cover all the bases.

**Comment by chyyran** [comment]
Here: #46
