### ISSUE TITLE
In 1.2 dev build, New players aren't connecting to IRC

### ISSUE THREAD

**Issue by WizardCM** [WMCAlliance/BukkitIRCd#61]
You can find the error at http://wizrd.tk/bqy401

**Comment by chyyran** [comment]
Try adding a try catch at [Line 138 of BukkitIRCdPlayerListener.java](https://github.com/WMCAlliance/BukkitIRCd/blob/config-rewrite/src/com/Jdbye/BukkitIRCd/BukkitIRCdPlayerListener.java#L138)

I can't do much right now, but I'll try when I get some more time

**Comment by WizardCM** [comment]
Oh I understand what's wrong, it happens when the player HAS no modes. Maybe I should have actually looked at the line that was erroring. xD
The main reason I put it on here was so I could check it later myself.

**Comment by glguy** [comment]
I believe this issue can be closed now
