### ISSUE TITLE
Centralize message formatting

### ISSUE THREAD

**Issue by chyyran** [WMCAlliance/BukkitIRCd#63]
What I mean by this is that instead of doing .replace("{Message}").replace("{"Name}"), etc, for each thing, just do something like formatChat(Input, Name, Message) where formatChat() is

```
public string formatChat(String input, String name, String message){
String output = input;
output = input.replace("{name}", name);
output = input.replace("{message}", message);
return output;
}
```

I've been meaning to do this, but I'm waiting for the config-rewrite branch to be completed and merged before I do so, since this directly affects that.

**Comment by WizardCM** [comment]
Yep, I can see the use in this. Over the next couple of weeks I hope to get the config-rewrite branch functioning properly, then we can get to work on everything else.

**Comment by WizardCM** [comment]
So, for this idea, would it be something like

``` java
formatChat(msgIRCLeaveReason,
     IRCd.getGroupPrefix(ircuser.getTextModes()),
     ircuser.nick,
     IRCd.getGroupSuffix(ircuser.getTextModes()),
     convertColors(reason, true),
     null);

public string formatChat(String input, 
          String prefix,
          String user,
          String suffix,
          String reason,
          String message){
```

where, depending on what it is, some locations will have 'null'
or, have a different formatFoo for each type of message? say, formatUserReason for those that only have prefix, suffix, user and reason?
