### ISSUE TITLE
A whois from IRC -> player bot gets no response

### ISSUE THREAD

**Issue by WizardCM** [WMCAlliance/BukkitIRCd#7]
that is, a /whois WizardCM-mc

**Comment by WizardCM** [comment]
<_route_replies> This module hit a timeout which is possibly a bug.
<_route_replies> Last request: whois boonimajneB1-mc boonimajneB1-mc
<_route_replies> Expected replies: 
<_route_replies> 311
<_route_replies> 319
<_route_replies> 312
<_route_replies> 338
<_route_replies> 318 (last)
<_route_replies> 401 (last)
<_route_replies> 402 (last)

**Comment by WizardCM** [comment]
Fixed in build 47.

**Comment by WizardCM** [comment]
This has returned in build 77.
http://netbook.home.wizardcm.com:8080/job/BukkitIRCd/77/

<_route_replies> This module hit a timeout which is possibly a bug.
<_route_replies> Last request: whois OliverHolland-mc OliverHolland-mc
<_route_replies> Expected replies: 
<_route_replies> 311
<_route_replies> 312
<_route_replies> 313
<_route_replies> 317
<_route_replies> 319
<_route_replies> 338
<_route_replies> 301
<_route_replies> 318 (last)
<_route_replies> 401 (last)
<_route_replies> 402 (last)
<_route_replies> 431 (last)

**Comment by glguy** [comment]
This bug was fixed in commit 818befc2e78aa38b9d7b472956408042682d8163 afaik

**Comment by WizardCM** [comment]
Yep, fixed, thanks again @glguy! :)
