### ISSUE TITLE
Kicking a player from IRC doesn't show anything ingame

### ISSUE THREAD

**Issue by WizardCM** [WMCAlliance/BukkitIRCd#72]
There are two ways we could go about this;
1. Display a custom kick message ingame, based on messages,yml
2. Using the kick-commands option in config.yml, kick the player using that command instead of whatever we're doing now - however, would we then be able to show a custom user name?

I'm leaning towards 2 more, but 1 might be easier and faster as a quick-fix.

**Comment by chyyran** [comment]
I think 1 would be the better way to do it.

``` java
void kickIngamePlayer(Player player, String reason, String kicker){
    player.kickPlayer("Kicked IRC by " + kicker + ": " + reason);
    Bukkit.getServer().broadcastMessage(player.getDisplayName() + "was kicked by " + kicker ": " +reason);
}
```

**Comment by WizardCM** [comment]
This is partly fixed, but is not yet configurable.

**Comment by WizardCM** [comment]
As it turns out, this was already implemented, but not working properly. in https://github.com/WMCAlliance/BukkitIRCd/commit/dbec19474b4bb746072f21486336777c0f2ee3bd @glguy fixed the issue.
