### ISSUE TITLE
People in staff channel no longer have enough perms

### ISSUE THREAD

**Issue by WizardCM** [WMCAlliance/BukkitIRCd#9]
Using our first compiled build 13, commands in the staff channel no longer work and instead error with "You do not have permissions to do that."

**Comment by WizardCM** [comment]
Fixed itself automatically somehow...
Edit: Breaks on restart

**Comment by WizardCM** [comment]
It seems there ARE permissions, but not for all permissions.

Proper console commands like !stop don't work, however commands like !whois (rCmds) do.

**Comment by BlaneyXYZ** [comment]
Could it possibly be a Bukkit issue?

**Comment by Lunaphied** [comment]
They might be blocked by the irc plugin I am putting the finishing touches
on portals but once that's released I will see about the irc plugin.

**Comment by chyyran** [comment]
Commit 33bc0e292d9ab3dc08d164005d901dc22c7d556c should fix this, it now sends commands as console, and fixes thread safety issues, rather than whatever it did before (might have been dependent on nick?)

**Comment by WizardCM** [comment]
@ron975 Download it from here and let me know what happens. I can't test it until later.
http://home.wizardcm.com:8080/job/BukkitIRCd/lastSuccessfulBuild/

**Comment by chyyran** [comment]
Commands like `!say` and `!stop` worked when I tested it, whereas they gave a generic permission denied message before.

**Comment by WizardCM** [comment]
Excellent, that's what we want. Awesome job @ron975 , thanks! :D
