### ISSUE TITLE
Configuration and Messages layout improvement ideas

### ISSUE THREAD

**Issue by WizardCM** [WMCAlliance/BukkitIRCd#91]
Basically, the idea is to make the files have sections relevant to what they're for.

In the case of configuration: server, chat, standalone and inspircd.

In the case of messages: to irc, to dynmap, from irc, each with their own sub-categories; to dynmap having public, connecting and kicking-banning, to-game having public, linking, connecting, kicking-banning, and private.

Note: in the below examples, not all data is shown; they're also from an older version of the configuration files.

config.yml
![25-07_22-18-34](https://f.cloud.github.com/assets/941350/855454/90f13e64-f524-11e2-97a4-c1bcd064cfdd.png)
![25-07_22-18-49](https://f.cloud.github.com/assets/941350/855453/90c159d8-f524-11e2-8ea2-c368860fb6d7.png)
![25-07_22-19-00](https://f.cloud.github.com/assets/941350/855452/90911b42-f524-11e2-8cab-36abea2994a8.png)

messages.yml

![25-07_22-21-23](https://f.cloud.github.com/assets/941350/855477/1e23ccde-f525-11e2-8daa-b25a027ee750.png)
![25-07_22-21-33](https://f.cloud.github.com/assets/941350/855476/1e1ee2be-f525-11e2-90c2-406377f2ed3c.png)
![25-07_22-21-49](https://f.cloud.github.com/assets/941350/855475/1e1d3df6-f525-11e2-9242-c26155b6cfdd.png)

**Comment by BlaneyXYZ** [comment]
Should be good in 9cd30faddbf09d6ac59565349023f6190d98fb4a
