### ISSUE TITLE
In latest builds, little to no 'automatic' messages show in staff channel

### ISSUE THREAD

**Issue by WizardCM** [WMCAlliance/BukkitIRCd#95]
@glguy

So, no idea why, but since one of the latest builds anything like broadcasts and stop messages don't show, but running commands do show. Very weird.

**Comment by glguy** [comment]
I'll poke around today. One issue I'd that you don't know if a command succeeded now since we don't run it asynchronously. I'll need to add code to the command executor to send the success status back to console channel. I don't know what's going on with broadcasts. I'll work on it tonight.

**Comment by glguy** [comment]
Fixed in f1ef0c756068b77660aac12e1a568e02e9b64499

**Comment by WizardCM** [comment]
I can confirm this is fixed.
